/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Graphics;

/**
 *
 * @author PC
 */
public class Corriendo extends javax.swing.JFrame {

    /**
     * Creates new form Corriendo
     */
    public Corriendo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Reloj = new javax.swing.JTextField();
        txt_CD = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tA_Durante = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tA_Final = new javax.swing.JTextArea();
        jC_Pausa = new javax.swing.JCheckBox();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonSalir.setBackground(new java.awt.Color(204, 0, 51));
        BotonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotonSalir.setForeground(new java.awt.Color(240, 240, 240));
        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 70, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Reloj:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 50, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Conexiones Descartadas: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 160, -1));

        txt_Reloj.setEditable(false);
        txt_Reloj.setBackground(new java.awt.Color(51, 51, 51));
        txt_Reloj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Reloj.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(txt_Reloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 150, 30));

        txt_CD.setEditable(false);
        txt_CD.setBackground(new java.awt.Color(51, 51, 51));
        txt_CD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_CD.setForeground(new java.awt.Color(240, 240, 240));
        txt_CD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CDActionPerformed(evt);
            }
        });
        getContentPane().add(txt_CD, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 150, 30));

        jTabbedPane2.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane2.setForeground(new java.awt.Color(240, 240, 240));
        jTabbedPane2.setFocusCycleRoot(true);
        jTabbedPane2.setFocusable(false);

        tA_Durante.setEditable(false);
        tA_Durante.setBackground(new java.awt.Color(51, 51, 51));
        tA_Durante.setColumns(20);
        tA_Durante.setForeground(new java.awt.Color(240, 240, 240));
        tA_Durante.setRows(5);
        tA_Durante.setTabSize(4);
        jScrollPane3.setViewportView(tA_Durante);
        tA_Durante.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane2.addTab("Durante", jScrollPane3);

        tA_Final.setBackground(new java.awt.Color(51, 51, 51));
        tA_Final.setColumns(20);
        tA_Final.setForeground(new java.awt.Color(240, 240, 240));
        tA_Final.setRows(5);
        tA_Final.setTabSize(4);
        jScrollPane1.setViewportView(tA_Final);

        jTabbedPane2.addTab("Final", jScrollPane1);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 920, 350));

        jC_Pausa.setBackground(new java.awt.Color(0, 153, 153));
        jC_Pausa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jC_Pausa.setText("Pausa");
        getContentPane().add(jC_Pausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 80, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1098, 537));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        Interfaz.seguir = false;
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void txt_CDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CDActionPerformed

    public void impDurante(String s) {
        tA_Durante.append(s);
        tA_Durante.setCaretPosition(tA_Durante.getDocument().getLength());
    }

    public void impFinal(String s) {
        tA_Final.append(s);
        tA_Final.setCaretPosition(tA_Final.getDocument().getLength());
    }

    public void impReloj(String s) {
        txt_Reloj.setText(s);
    }

    public void impCD(String s) {
        txt_CD.setText(s);
    }

    public boolean getPausa() {
        if (jC_Pausa.isSelected()) {
            return true;
        } else {
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSalir;
    private javax.swing.JCheckBox jC_Pausa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea tA_Durante;
    private javax.swing.JTextArea tA_Final;
    private javax.swing.JTextField txt_CD;
    private javax.swing.JTextField txt_Reloj;
    // End of variables declaration//GEN-END:variables
}
