/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

import java.util.Locale;
import java.util.Scanner;
import java.util.InputMismatchException;

/**
 *
 * @author PC
 */
public class Datos extends javax.swing.JFrame {

    
    /** Creates new form Datos */
    public Datos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        BotonSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_M = new javax.swing.JTextField();
        txt_Iter = new javax.swing.JTextField();
        txt_Tiempo = new javax.swing.JTextField();
        txt_K = new javax.swing.JTextField();
        txt_P = new javax.swing.JTextField();
        txt_T = new javax.swing.JTextField();
        botonContinuar = new javax.swing.JButton();
        jC_ModoLento = new javax.swing.JCheckBox();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Por favor ingrese los siguientes datos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        BotonSalir.setBackground(new java.awt.Color(204, 0, 51));
        BotonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotonSalir.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 70, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Maximo de sentenicas para ejecutar (m):");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 310, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Numero de veces que desea correr la simulacion: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 310, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Maximo de Tiempo de la simulacion:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 310, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Maximo conexiones perimtidas (k):");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 310, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Tiempo maximo por conexion (t):");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 310, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Maximo de procesos disponibles (p):");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 310, -1));

        txt_M.setBackground(new java.awt.Color(51, 51, 51));
        txt_M.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_M.setForeground(new java.awt.Color(240, 240, 240));
        txt_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MActionPerformed(evt);
            }
        });
        getContentPane().add(txt_M, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 50, -1));

        txt_Iter.setBackground(new java.awt.Color(51, 51, 51));
        txt_Iter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Iter.setForeground(new java.awt.Color(240, 240, 240));
        txt_Iter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IterActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Iter, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 50, -1));

        txt_Tiempo.setBackground(new java.awt.Color(51, 51, 51));
        txt_Tiempo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Tiempo.setForeground(new java.awt.Color(240, 240, 240));
        txt_Tiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TiempoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 50, -1));

        txt_K.setBackground(new java.awt.Color(51, 51, 51));
        txt_K.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_K.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(txt_K, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 50, -1));

        txt_P.setBackground(new java.awt.Color(51, 51, 51));
        txt_P.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_P.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(txt_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 50, -1));

        txt_T.setBackground(new java.awt.Color(51, 51, 51));
        txt_T.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_T.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(txt_T, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 50, -1));

        botonContinuar.setBackground(new java.awt.Color(0, 153, 153));
        botonContinuar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonContinuar.setForeground(new java.awt.Color(240, 240, 240));
        botonContinuar.setText("Continuar");
        botonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(botonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 110, 30));

        jC_ModoLento.setBackground(new java.awt.Color(0, 153, 153));
        jC_ModoLento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jC_ModoLento.setText("Modo Lento");
        getContentPane().add(jC_ModoLento, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 100, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        Interfaz.seguir = false;
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void botonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContinuarActionPerformed
        Interfaz.tM = this.getTiempo();
        Interfaz.iter = Interfaz.datos.getIter();
        Interfaz.t = Interfaz.datos.getT();
        Interfaz.k = Interfaz.datos.getK();
        Interfaz.m = Interfaz.datos.getM();
        Interfaz.p = Interfaz.datos.getM();
        Interfaz.v3 = true;
        Interfaz.modoLento = jC_ModoLento.isSelected();
        Interfaz.corr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonContinuarActionPerformed

    private void txt_IterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IterActionPerformed
        
    }//GEN-LAST:event_txt_IterActionPerformed

    private void txt_TiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TiempoActionPerformed

    private void txt_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MActionPerformed

    public int getIter(){
        String texto = txt_Iter.getText();
        int resultado = 0;
        Scanner s = new Scanner(texto);
        resultado += s.nextInt();
        return resultado;
    }
    
    public double getTiempo(){
        String texto = txt_Tiempo.getText();
        double resultado = 0.0;
        Scanner s = new Scanner(texto).useLocale(Locale.US);
        resultado += s.nextDouble();
        return resultado;
    }
    
    public int getK(){
        String texto = txt_K.getText();
        int resultado = 0;
        Scanner s = new Scanner(texto);
        resultado += s.nextInt();
        return resultado;
    }
    
    public int getM(){
        String texto = txt_M.getText();
        int resultado = 0;
        Scanner s = new Scanner(texto);
        resultado += s.nextInt();
        return resultado;
    }
    
    public int getP(){
        String texto = txt_P.getText();
        int resultado = 0;
        Scanner s = new Scanner(texto);
        resultado += s.nextInt();
        return resultado;
    }
    
    public double getT(){
        String texto = txt_T.getText();
        double resultado = 0.0;
        Scanner s = new Scanner(texto).useLocale(Locale.US);
        resultado += s.nextDouble();
        return resultado;
    }
    
    public boolean getV3(){
        return Interfaz.v3;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton botonContinuar;
    private javax.swing.JCheckBox jC_ModoLento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JTextField txt_Iter;
    private javax.swing.JTextField txt_K;
    private javax.swing.JTextField txt_M;
    private javax.swing.JTextField txt_P;
    private javax.swing.JTextField txt_T;
    private javax.swing.JTextField txt_Tiempo;
    // End of variables declaration//GEN-END:variables
}
